---
- name: Django | Packages | Install required system packages.
  apt: >
    pkg=${item}
    state=installed
    update-cache=yes
  with_items:
    - build-essential
    - git
    - python-dev
    - python-setuptools
    - python-psycopg2
    - python-virtualenv
    - python-pip
    - postfix
    - libpq-dev
  tags:
    - base
    - packages
    - provision
    - app


- name: Scrapy | Packages | Install required system packages.
  apt: >
    pkg=${item}
    state=installed
    update-cache=yes
  with_items:
    - libffi-dev
    - libxml2-dev
    - libxslt1-dev

  tags:
    - scrapy
    - base
    - packages
    - provision
    - app



- name: Scrapy | Packages | Install Phantomjs
  command: "{{item}}"
  with_items:
    - wget https://phantomjs.googlecode.com/files/phantomjs-1.9.0-linux-x86_64.tar.bz2 chdir=/usr/local/share
    - tar xjf phantomjs-1.9.0-linux-x86_64.tar.bz2 chdir=/usr/local/share
    - ln -s /usr/local/share/phantomjs-1.9.0-linux-x86_64/bin/phantomjs /usr/local/share/phantomjs chdir=/usr/local/share
    - ln -s /usr/local/share/phantomjs-1.9.0-linux-x86_64/bin/phantomjs /usr/local/bin/phantomjs chdir=/usr/local/share
    - ln -s /usr/local/share/phantomjs-1.9.0-linux-x86_64/bin/phantomjs /usr/bin/phantomjs chdir=/usr/local/share

  tags:
    - scrapy
    - packages
    - provision
    - app
    - phantomjs
