---
- name: ES |  Playbook  |  DbServers
  hosts: dbservers
  tasks:
    - name: "restart nginx service"
      service: >
        name=nginx
        state=restarted


    - name: "restart uwsgi service"
      service: >
        name={{project.name}}-uwsgi
        state=restarted

  tags:
    - srvreset
    - webserver

